# Generated by Django 6.1 on 2026-08-07 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='tracking.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'component',
                'verbose_name_plural': 'components',
                'ordering': ['name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='tracking.component', verbose_name='components'),
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('color', models.CharField(default='secondary', max_length=20, verbose_name='color')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='tracking.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'flag',
                'verbose_name_plural': 'flags',
                'ordering': ['name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='flags',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='tracking.flag', verbose_name='flags'),
        ),
    ]
