# Generated by Django 6.1 on 2026-08-09 08:08

import django.db.models.deletion
import tracking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_remove_ticket_flags_label_ticket_labels_delete_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('file', models.FileField(upload_to=tracking.models.attachment_path, verbose_name='file')),
                ('mime_type', models.CharField(editable=False, max_length=100, verbose_name='mime type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tracking.ticket', verbose_name='ticket')),
            ],
            options={
                'verbose_name': 'attachment',
                'verbose_name_plural': 'attachments',
                'ordering': ['-created_at'],
            },
        ),
    ]
