# Generated by Django 6.1 on 2026-08-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='estimation',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='estimation'),
        ),
    ]
