# Generated by Django 6.1 on 2026-08-10 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_add_sprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('related_to', 'Related to'), ('blocked_by', 'Blocked by'), ('tested_with', 'Found during testing of')], max_length=20, verbose_name='relation type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_relations', to='tracking.ticket', verbose_name='subject ticket')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_relations', to='tracking.ticket', verbose_name='target ticket')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('subject', 'target', 'relation_type')},
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='relation_tickets',
            field=models.ManyToManyField(blank=True, related_name='related_to', through='tracking.TicketRelation', through_fields=('subject', 'target'), to='tracking.ticket', verbose_name='related tickets'),
        ),
    ]
