# Generated by Django 6.1 on 2026-08-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_ticketrelation_ticket_relation_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketrelation',
            name='relation_type',
            field=models.CharField(choices=[('related_to', 'Related to'), ('blocked_by', 'Blocked by'), ('tested_with', 'Found during testing of'), ('is_parent', 'Is parent'), ('is_child', 'Is child')], max_length=20, verbose_name='relation type'),
        ),
    ]
