# Generated by Django 6.1 on 2026-08-11 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_alter_ticketrelation_relation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='parent_epic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_tickets', to='tracking.ticket', verbose_name='epic'),
        ),
    ]
