# Generated by Django 6.1 on 2026-08-14 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_ticket_due_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('state_changed', 'State changed'), ('title_changed', 'Title changed'), ('description_changed', 'Description changed'), ('key_changed', 'Related ticket added'), ('comment_added', 'Comment added'), ('component_added', 'Component added'), ('component_removed', 'Component removed'), ('label_added', 'Label added'), ('label_removed', 'Label removed'), ('relation_added', 'Relation added'), ('relation_removed', 'Relation removed'), ('sprint_changed', 'Sprint changed'), ('attachment_added', 'Attachment added'), ('attachment_removed', 'Attachment removed'), ('ticket_created', 'Ticket created'), ('ticket_deleted', 'Ticket deleted')], db_index=True, max_length=30, verbose_name='action')),
                ('field_name', models.CharField(blank=True, default='', max_length=50, verbose_name='field')),
                ('old_value', models.TextField(blank=True, default='', verbose_name='old value')),
                ('new_value', models.TextField(blank=True, default='', verbose_name='new value')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tracking.ticket', verbose_name='ticket')),
            ],
            options={
                'verbose_name': 'activity log entry',
                'verbose_name_plural': 'activity log entries',
                'ordering': ['created_at'],
            },
        ),
    ]
