# Generated by Django 6.1 on 2026-08-14 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0012_ticketactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='target date')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='release date')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('archived', models.BooleanField(default=False, verbose_name='archived')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='tracking.project', verbose_name='project')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.sprint', verbose_name='sprint')),
            ],
            options={
                'verbose_name': 'version',
                'verbose_name_plural': 'versions',
                'ordering': ['-release_date', '-target_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='affects_versions',
            field=models.ManyToManyField(blank=True, related_name='affected_tickets', to='tracking.version', verbose_name='affects versions'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fix_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.version', verbose_name='fix version'),
        ),
    ]
