# Generated by Django 6.1 on 2026-08-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_version_ticket_affects_versions_ticket_fix_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='backlog_order',
            field=models.PositiveIntegerField(default=0, help_text='Position in backlog ordering. Higher numbers = higher priority.', verbose_name='backlog order', blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('task', 'Task'), ('bug', 'Bug'), ('story', 'Story'), ('epic', 'Epic'), ('subtask', 'Sub-task')], default='task', max_length=20, verbose_name='type'),
        ),
    ]
