# Generated by Django 6.1 on 2026-08-14 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0014_ticket_backlog_order_alter_ticket_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_body', models.TextField(blank=True, default='', verbose_name='old body')),
                ('new_body', models.TextField(verbose_name='new body')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_edits', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='tracking.comment', verbose_name='comment')),
            ],
            options={
                'verbose_name': 'comment edit history',
                'verbose_name_plural': 'comment edit histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
