# Generated by Django 6.1 on 2026-08-21 08:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0016_notification_watcher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('ticket', 'recipient', 'verb'), name='unique_ticket_recipient_verb'),
        ),
    ]
