# Generated by Django 6.1 on 2026-08-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0017_notification_unique_ticket_recipient_verb'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['state', 'project'], name='ticket_state_project_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assignee', 'state'], name='ticket_assignee_state_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['type', 'state'], name='ticket_type_state_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['priority'], name='ticket_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['sprint'], name='ticket_sprint_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['fix_version'], name='ticket_fix_version_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['reporter'], name='ticket_reporter_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at'], name='ticket_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['updated_at'], name='ticket_updated_at_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['state', 'priority'], name='ticket_state_priority_idx'),
        ),
    ]
