# Generated by Django 6.1 on 2026-08-21 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0018_ticket_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_days', models.PositiveIntegerField(default=0, help_text='Calendar days between start_date and end_date.', verbose_name='duration (days)')),
                ('ticket_count', models.PositiveIntegerField(default=0, help_text='Excluding tickets in CLOSED state.', verbose_name='ticket count')),
                ('completed_count', models.PositiveIntegerField(default=0, help_text='Tickets in CLOSED state.', verbose_name='completed count')),
                ('total_points', models.PositiveIntegerField(default=0, help_text='SUM(estimation) for all sprint tickets with estimation > 0.', verbose_name='total points')),
                ('completed_points', models.PositiveIntegerField(default=0, help_text='SUM(estimation) for CLOSED tickets with estimation > 0.', verbose_name='completed points')),
                ('waste_ratio', models.FloatField(default=0.0, help_text='Percentage of high-priority (HIGH / CRITICAL) open tickets in the sprint.', verbose_name='waste ratio')),
                ('velocity_window', models.IntegerField(default=14, help_text='Days look-back window used for velocity calculations.', verbose_name='velocity window')),
                ('completed_date', models.DateField(blank=True, help_text='Date when this snapshot was taken.', null=True, verbose_name='completed date')),
                ('sprint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='tracking.sprint', verbose_name='sprint')),
            ],
            options={
                'verbose_name': 'sprint metrics',
                'verbose_name_plural': 'sprint metrics',
            },
        ),
    ]
