# Generated by Django 6.1 on 2026-08-21 11:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0019_sprintmetrics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='component',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sprint',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ticketrelation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='watcher',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='component',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_component_project_name'),
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_label_project_name'),
        ),
        migrations.AddConstraint(
            model_name='sprint',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_sprint_project_name'),
        ),
        migrations.AddConstraint(
            model_name='sprint',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('project',), name='one_active_sprint_per_project'),
        ),
        migrations.AddConstraint(
            model_name='ticketrelation',
            constraint=models.UniqueConstraint(fields=('subject', 'target', 'relation_type'), name='unique_relation_direction'),
        ),
        migrations.AddConstraint(
            model_name='watcher',
            constraint=models.UniqueConstraint(fields=('ticket', 'user'), name='unique_watcher_ticket_user'),
        ),
    ]
