# Generated by Django 6.1 on 2026-08-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0022_worklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='original_estimate',
            field=models.FloatField(blank=True, default=None, help_text='Per-entry original estimate in hours. Used for epic rollups.', null=True, verbose_name='original estimate (hours)'),
        ),
        migrations.AddField(
            model_name='worklog',
            name='remaining_estimate',
            field=models.FloatField(blank=True, default=None, help_text='Per-entry remaining estimate in hours. Falls back to calculation if blank.', null=True, verbose_name='remaining estimate (hours)'),
        ),
    ]
