# Generated by Django 6.1 on 2026-09-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0024_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="sprint",
            name="is_closed",
            field=models.BooleanField(default=False, verbose_name="is closed"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("blocked", "Blocked"),
                    ("open", "Open"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                ],
                default="draft",
                max_length=20,
                verbose_name="state",
            ),
        ),
    ]
